<?php
/**
 * Created by PhpStorm.
 * User: xiao
 * Date: 2016/10/11
 * Time: 21:28
 */
namespace  App;
use Illuminate\Database\Eloquent\Model;

class Student extends Model {
    //指定表明
    protected $table="student";
    //指定主键
    protected $primaryKey='id';
    //自动维护时间戳
    public $timestamps = false;
    //允许批量复制的字段
    protected $fillable = ['name'];
    //进制批量赋值
    protected  $guarded = ['age'];
    //设置更新当前时间戳
    public function getDateFormat()
    {
        return time();//parent::getDateFormat(); // TODO: Change the autogenerated stub
    }
    //获取元数据
    protected function asDateTime($value)
    {
        return $value;//parent::asDateTime($value); // TODO: Change the autogenerated stub
    }
}